name: compras
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  flutter_riverpod: ^2.5.1
  shared_preferences: ^2.2.2
  uuid: ^4.5.1
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  path_provider: ^2.1.1
  fl_chart: ^0.68.0
  image_picker: ^1.0.7
  sensors_plus: ^4.0.2
  intl: ^0.19.0
  flutter_svg: ^2.0.10+1
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  hive_generator: ^2.0.1
  build_runner: ^2.4.7
  flutter_launcher_icons: ^0.9.3

flutter:
  uses-material-design: true
  assets:
    - assets/logo/
flutter_icons:
  image_path: "assets/logo/cart_logo.png"
  android: true
  ios: true
  image_quality: 100
  adaptive_icon: true
